name: osu_preview
description: Real-time osu! beatmap preview on Android (Flutter + Rust/wgpu).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
